### ISSUE TITLE
It is not possible to create new rules in TYPO3 v12

### ISSUE THREAD

**Issue by Prospero256** [xperseguers/t3ext-image_autoresize#92]
Hello,

thank you for developing this fine extension. Unfortunately there seems to be a problem in this new environment:

I am using version 2.2.2 in TYPO3 v12.4.8, as composer-installation on Ubuntu 22 with PHP 8.2.12.
It is possible to access the extension configuration and set some general rules, which -as far as I can tell atm.- do work, but
the button for creating new rules on the last tab does not (nothing happens, not even error messages).

Update: There actually _are_ error messages:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1478105491: Specified identifier {"type":"tca","tableName":"tx_imageautoresize","fieldName":"rulesets","dataStructureKey":"default"} does not resolve to a valid TCA array value | TYPO3\CMS\Core\Configuration\FlexForm\Exception\InvalidIdentifierException thrown in file [...]/vendor/typo3/cms-core/Classes/Configuration/FlexForm/FlexFormTools.php in line 660. Requested URL: [...]/typo3/ajax/record/flex/containeradd?token=--AnonymizedToken-- 

and

Core: Error handler (BE): PHP Warning: Undefined array key "tx_imageautoresize" in [...]/vendor/typo3/cms-backend/Classes/Controller/FormFlexAjaxController.php line 57 

The latter sounds like a missing DB entry, but the DB report tool says the DB is fine.

**Comment by nannione** [comment]
I can confirm the issue. Additionally the format conversation seems not to work either in TYPO3 v12.

**Comment by xperseguers** [comment]
@nannione What is "the format conversation"?

**Comment by nannione** [comment]
Updated my comment with the dorret term "image type conversion mapping".

**Comment by nannione** [comment]
The xxtension breaks the scheduler as soon you create a new task.

Error Message:
Fatal error: Declaration of Causal\ImageAutoresize\Task\fakeSchedulerModuleController::addMessage($message, $severity = TYPO3\CMS\Core\Messaging\FlashMessage::OK) must be compatible with TYPO3\CMS\Scheduler\Controller\SchedulerModuleController::addMessage(TYPO3\CMS\Backend\Template\ModuleTemplate $moduleTemplate, string $message, TYPO3\CMS\Core\Type\ContextualFeedbackSeverity $severity = TYPO3\CMS\Core\Type\ContextualFeedbackSeverity::OK): void in /usr/local/www/apache24/noexec/testserver/nolight.testserver001.net/vendor/causal/image_autoresize/Classes/Task/BatchResizeAdditionalFieldProvider.php on line 168

**Comment by xperseguers** [comment]
> The xxtension breaks the scheduler as soon you create a new task.

@nannione Please do not hijack the ticket with something unrelated to it.

The problem with the scheduler has been fixed, some details in #96

**Comment by nannione** [comment]
Sorry, please delete or move my comment.

**Comment by xperseguers** [comment]
Info to reproduce:

1. Enable CSP (by default "on" for new install): make sure to toggle on `[SYS][features][security.backend.enforceContentSecurityPolicy]`
2. Go to Extension Manager and open the configuration form for this extension
3. Either check the console or use the Backend module Admin Tools > Content Security Policy

**Comment by hanneskoksch** [comment]
I think the problem still exists. I ran into it with a new Typo3 13.4.8 composer installation (also with v12).

web server: nginx and apache
php: 8.3.16

```
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1478105491: Specified identifier {"type":"tca","tableName":"tx_imageautoresize","fieldName":"rulesets","dataStructureKey":"default"} does not resolve to a valid TCA array value | TYPO3\CMS\Core\Configuration\FlexForm\Exception\InvalidIdentifierException thrown in file /var/www/html/vendor/typo3/cms-core/Classes/Configuration/FlexForm/FlexFormTools.php in line 490. Requested URL: https://image-compression-typo3-test.ddev.site/typo3/ajax/record/flex/containeradd?token=--AnonymizedToken--
```
```
Core: Error handler (BE): PHP Warning: Undefined array key "tx_imageautoresize" in /var/www/html/vendor/typo3/cms-backend/Classes/Controller/FormFlexAjaxController.php line 65
```
